<?php
/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Account matching') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
    <form action="<?php echo $this->getPostActionUrl(); ?>" method="post" id="confirm-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <input name="action" type="hidden" value="account_confirm">
        <div class="account-login">
            <div class="content">
                <p><?php echo $this->__('Please enter your shop password to match it with your Amazon account.') ?></p>
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" disabled="disabled" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            </div>
            <div class="buttons-set">
                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                <button type="button" class="button cancel" onclick="cancelMatching();"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">//<![CDATA[
        function cancelMatching() {
            amazon.Login.logout();
            setLocation('<?php echo $this->escapeUrl($this->getBackUrl()); ?>');
        }
    //]]></script>
</div>