<?php
/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<?php if ($jsScripts = $this->getJsScripts()): ?>
    <script type="text/javascript">//<![CDATA[
        <?php echo $jsScripts; ?>
    //]]></script>
<?php endif; ?>
<script async type="text/javascript" src="<?php echo $this->getWidgetUrl(); ?>"></script>
