<?php
/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<?php if ($this->willBeCapturedImmediately()): ?>
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <span><?php echo $this->__('Please note that the total amount of the order will be charged at order placement.'); ?></span>
                </li>
            </ul>
        </li>
    </ul>
<?php endif; ?>
