<?php
/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<button id="amazonpayments-checkout-place-order-button" type="submit" title="<?php echo $this->helper('checkout')->__('Place Order') ?>" class="button btn-checkout" disabled="disabled" onclick="APA.saveOrder();"><span><span><?php echo $this->helper('checkout')->__('Place Order') ?></span></span></button>
